[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[git_branch]
symbol = "ğŸŒ±  "

[git_status]
conflicted = "ğŸ³  "
ahead = "ğŸ  ğŸ’¨ "
behind = "ğŸ˜° "
diverged = "ğŸ˜µ "
untracked = "ğŸ¤· "
stashed = "ğŸ“¦ "
modified = "ğŸ“ "
staged = "â• "
renamed = "ğŸ‘… "
deleted = "ğŸ—‘  "

[python]
style="bold green"
symbol = "ğŸ "

[memory_usage]
disabled=true
show_percentage = true
show_swap = false
threshold = -1
symbol = "ğŸ  "
separator = "/"
style = "bold dimmed green"

[aws]
style="bold blue"

[cmd_duration]
style="blue"
